import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import FloatingAIBot from '../components/FloatingAIBot';
import SEOHead from '../components/SEOHead';

const pillars = [
  { icon: 'ti-map-pin', tone: 'green', title: 'Khám phá Nghệ An', text: 'Kim Liên, Cửa Lò, miền Tây xứ Nghệ, Ví Giặm và những hành trình giàu bản sắc.', cta: 'Bắt đầu hành trình', to: '/posts?category=Du%20lịch%20%26%20Trải%20nghiệm', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=82' },
  { icon: 'ti-building-skyscraper', tone: 'blue', title: 'Kết nối Doanh nghiệp', text: 'Tìm kiếm đối tác, giới thiệu năng lực và mở rộng chuỗi cung ứng trong nước, quốc tế.', cta: 'Tìm đối tác', to: '/members', image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=82' },
  { icon: 'ti-chart-arrows-vertical', tone: 'gold', title: 'Đầu tư tại Nghệ An', text: 'Thông tin minh bạch về hạ tầng, khu kinh tế, nhân lực và các cơ hội đầu tư trọng điểm.', cta: 'Khám phá cơ hội', to: '/posts?category=Xúc%20tiến%20Đầu%20tư%20%26%20FDI', image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=82' }
];
const regions = [
  ['Thành phố Vinh & Vùng phụ cận', 'Trung tâm kinh tế, văn hóa và dịch vụ năng động', '/images/nghean-vinh-city.png'],
  ['Cửa Lò & Du lịch biển', 'Bãi biển đẹp, ẩm thực biển và không gian nghỉ dưỡng', '/images/nghean-cua-lo.png'],
  ['Nam Đàn – Quê hương Chủ tịch Hồ Chí Minh', 'Hành trình về nguồn và các giá trị lịch sử đặc biệt', '/images/nghean-nam-dan.png'],
  ['Miền Tây Nghệ An', 'Thiên nhiên hùng vĩ, văn hóa bản địa và du lịch cộng đồng', '/images/nghean-western.png']
];
const heritage = [
  ['ti-music', 'Dân ca Ví–Giặm Nghệ Tĩnh', 'Di sản văn hóa phi vật thể đại diện của nhân loại, được gìn giữ qua nhiều thế hệ.'], ['ti-star', 'Quê hương Chủ tịch Hồ Chí Minh', 'Không gian lưu niệm đặc biệt, kết nối lịch sử dân tộc với quê hương xứ Nghệ.'], ['ti-map-2', 'Truyền thống hiếu học & Danh nhân', 'Vùng đất địa linh nhân kiệt với những con người giàu nghị lực, trí tuệ và nghĩa tình.']
];
const fdiItems = [['Hạ tầng KCN & KKT', 'Khu kinh tế Đông Nam và các KCN VSIP, WHA với kết nối thuận lợi.'], ['Lĩnh vực ưu tiên', 'Công nghiệp cao, điện tử, chế biến, logistics và năng lượng sạch.'], ['Nguồn nhân lực', 'Lực lượng lao động trẻ, hệ thống giáo dục và đào tạo nghề phong phú.'], ['Hỗ trợ thủ tục', 'Chỉ dẫn nguồn chính thức, đồng hành cùng nhà đầu tư trong quá trình tìm hiểu.']];

export const Home = () => {
  const navigate = useNavigate();
  const [query, setQuery] = useState('');
  const [posts, setPosts] = useState([]);
  const [members, setMembers] = useState([]);
  const [activeRegion, setActiveRegion] = useState(0);
  useEffect(() => { Promise.allSettled([fetch('/api/posts?limit=3').then(r => r.json()), fetch('/api/members?limit=3').then(r => r.json())]).then(([a, b]) => { if (a.status === 'fulfilled' && a.value?.success) setPosts(a.value.data || []); if (b.status === 'fulfilled' && b.value?.success) setMembers(b.value.data || []); }); }, []);
  const search = e => { e.preventDefault(); if (query.trim()) navigate(`/posts?search=${encodeURIComponent(query.trim())}`); };

  return <div className="na-home"><SEOHead title="Nghean.today – Kết nối Nghệ An với Việt Nam và Thế giới" description="Nền tảng số đa ngôn ngữ quảng bá Nghệ An, kết nối doanh nghiệp và xúc tiến đầu tư." /><Navbar /><main>
    <section className="na-hero"><div className="na-hero-orb orb-one" aria-hidden="true"/><div className="na-hero-orb orb-two" aria-hidden="true"/><div className="na-hero-lines" aria-hidden="true"/><div className="na-container na-hero-inner"><span className="na-eyebrow light">Nền tảng số thế hệ mới</span><h1 className="na-hero-reveal title-one">NGHEAN.TODAY</h1><h2 className="na-hero-reveal title-two">Nền tảng kết nối Nghệ An với Việt Nam và<br className="desktop-only" /> Thế giới</h2><p>Khám phá vùng đất giàu truyền thống, kết nối cộng đồng doanh nghiệp, tiếp cận cơ hội đầu tư và trải nghiệm hệ sinh thái trí tuệ nhân tạo đa ngôn ngữ dành riêng cho Nghệ An.</p><div className="na-hero-actions"><Link to="/posts?category=Du%20lịch%20%26%20Trải%20nghiệm" className="na-btn white">Khám phá Nghệ An</Link><Link to="/posts?category=Xúc%20tiến%20Đầu%20tư%20%26%20FDI" className="na-btn orange">Tìm cơ hội đầu tư</Link><Link to="/members" className="na-btn green">Kết nối doanh nghiệp</Link><Link to="/ai-chat" className="na-btn red"><i className="ti ti-sparkles" /> Hỏi trợ lý AI</Link></div><form className="na-search" onSubmit={search}><i className="ti ti-search" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Bạn muốn tìm hiểu điều gì về Nghệ An?" /><button>Tìm kiếm thông minh</button></form><div className="na-suggestions">Gợi ý nhanh: <button onClick={() => setQuery('Du lịch Cửa Lò')}>Du lịch Cửa Lò</button><button onClick={() => setQuery('Quê Bác Kim Liên')}>Quê Bác Kim Liên</button><button onClick={() => setQuery('Doanh nghiệp Nghệ An')}>Doanh nghiệp Nghệ An</button></div></div></section>
    <section className="na-section"><div className="na-container"><Heading title="Ba Trụ Cột Chiến Lược">Định hướng phát triển toàn diện nhằm đưa Nghệ An bứt phá trong kỷ nguyên số và hội nhập quốc tế.</Heading><div className="na-pillar-grid">{pillars.map(p => <article className="na-pillar" key={p.title}><div className="na-pillar-image" style={{ backgroundImage: `url(${p.image})` }}><span><i className={`ti ${p.icon}`} /> {p.title}</span></div><div className="na-card-body"><p>{p.text}</p><Link className={`na-text-link ${p.tone}`} to={p.to}>{p.cta} <i className="ti ti-arrow-right" /></Link></div></article>)}</div></div></section>
    <section className="na-section muted"><div className="na-container"><Heading title="Khám Phá Nghệ An">Chọn các khu vực trọng điểm để khám phá điểm đến, tiềm năng du lịch và thông tin chi tiết.</Heading><div className="na-region-layout"><div className="na-region-list">{regions.map((r, i) => <button key={r[0]} className={activeRegion === i ? 'active' : ''} onClick={() => setActiveRegion(i)}><strong>{r[0]}</strong><span>{r[1]}</span></button>)}</div><div className="na-region-preview" style={{ backgroundImage: `linear-gradient(0deg, rgba(6,18,30,.94) 0%, rgba(6,18,30,.12) 68%), url(${regions[activeRegion][2]})` }}><div className="na-region-overlay"><span>KHÁM PHÁ</span><h3>{regions[activeRegion][0]}</h3><p>{regions[activeRegion][1]}. Khám phá dữ liệu, câu chuyện và các điểm kết nối nổi bật.</p><Link to="/posts">Xem chi tiết <i className="ti ti-arrow-right" /></Link></div></div></div></div></section>
    <section className="na-section dark"><div className="na-container"><Heading title="Văn Hóa và Di Sản" light kicker="Bản sắc xứ Nghệ">Không gian giàu cảm xúc lưu giữ Dân ca Ví–Giặm, truyền thống hiếu học và di sản cách mạng hào hùng.</Heading><div className="na-heritage-grid">{heritage.map(h => <article key={h[1]}><i className={`ti ${h[0]}`} /><h3>{h[1]}</h3><p>{h[2]}</p><Link to="/posts?category=Văn%20hóa%20%26%20Di%20sản">Khám phá câu chuyện <i className="ti ti-arrow-right" /></Link></article>)}</div></div></section>
    <section className="na-section na-members-section"><div className="na-container"><Heading title="Doanh Nghiệp Tiêu Biểu Nghệ An">Ưu tiên doanh nghiệp được ghim nổi bật và các hội viên có thứ hạng cao trong hệ sinh thái.</Heading><div className="na-member-tools"><input placeholder="Tìm doanh nghiệp, sản phẩm..." /><Link to="/members">Xem danh bạ</Link></div>{members.length > 0 ? <div className="na-company-grid">{members.slice(0, 3).map(m => <article className={m.is_featured ? 'featured' : ''} key={m.id || m.name}>{m.is_featured === 1 && <span className="na-featured-ribbon"><i className="ti ti-pin-filled" /> Nổi bật</span>}<div className="na-avatar">{(m.name || 'DN').slice(0, 2).toUpperCase()}</div><div className="na-company-info"><div className="na-company-meta"><span className={`na-tier tier-${(m.tier || 'standard').toLowerCase()}`}>{m.tier || 'Standard'}</span></div><h3>{m.name}</h3><p>{m.industry || m.description}</p></div><Link to={`/members?search=${encodeURIComponent(m.name)}`}>Kết nối <i className="ti ti-arrow-right" /></Link></article>)}</div> : <EmptyState text="Chưa có doanh nghiệp được công bố. Dữ liệu sẽ hiển thị sau khi được quản trị viên phê duyệt." />}</div></section>
    <section className="na-section muted"><div className="na-container"><Heading title="Trung Tâm Xúc Tiến Đầu Tư FDI" kicker="Điểm đến của các tập đoàn lớn">Cung cấp thông tin minh bạch, hạ tầng KCN hiện đại và chính sách ưu đãi hấp dẫn cho nhà đầu tư.</Heading><div className="na-fdi-grid">{fdiItems.map((x, i) => <article key={x[0]} className={`c${i}`}><h3>{x[0]}</h3><p>{x[1]}</p><Link to="/posts?category=Xúc%20tiến%20Đầu%20tư%20%26%20FDI">Xem chi tiết <i className="ti ti-arrow-right" /></Link></article>)}</div><div className="na-center-actions"><Link className="na-btn orange" to="/posts?category=Xúc%20tiến%20Đầu%20tư%20%26%20FDI">Tải hồ sơ đầu tư</Link><Link className="na-btn blue" to="/posts">Xem bản đồ các KCN</Link></div></div></section>
    <section className="na-section"><div className="na-container"><Heading title="Tin Tức & Sự Kiện">Cập nhật nhanh chóng các hoạt động kinh tế, văn hóa, đầu tư và đổi mới sáng tạo.</Heading>{posts.length > 0 ? <div className="na-news-grid">{posts.slice(0, 3).map((p, i) => <article key={p.id || i}>{(p.image_url || p.thumbnail || p.image) && <img src={p.image_url || p.thumbnail || p.image} alt="" />}<div><span>{p.category_name || p.category || 'Tin tức'}</span><h3>{p.title}</h3><p>{p.excerpt || p.summary}</p><Link to={p.slug ? `/posts/${p.slug}` : `/posts/${p.id}`}>Đọc tiếp <i className="ti ti-arrow-right" /></Link></div></article>)}</div> : <EmptyState text="Chưa có bài viết được công bố. Nội dung sẽ hiển thị sau khi được quản trị viên phê duyệt." />}</div></section>
  </main><Footer /><FloatingAIBot /></div>;
};

const Heading = ({ title, children, light, kicker }) => <div className={`na-heading ${light ? 'light' : ''}`}>{kicker && <span className="na-kicker">{kicker}</span>}<h2>{title}</h2><p>{children}</p></div>;
const EmptyState = ({ text }) => <div className="na-empty"><i className="ti ti-database-off" /><p>{text}</p></div>;
export default Home;
